import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";
import { client } from "../utils/client";
import Product from "../components/Product";
export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            flexWrap: "wrap",
          }}
        >
          {products?.map((product) => (
            <Product key={product._id} product={product} />
          ))}
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
  return {
    props: { products },
  };
};
